### ISSUE TITLE
Error in adding an item to workflowy

### ISSUE THREAD

**Issue by liatzionimorad** [WA-WF-Bot/Fredo-Public#101]
![image](https://user-images.githubusercontent.com/79567202/163221141-ed49dd2b-50e6-4477-b92c-57f396d21dd7.png)

From dev research is seems that session id used by the bot to access workflowy has expired.

Please elaborate on problem& solution

**Comment by JerryVDP** [comment]
The login session between the bot and workflow has expired, so the bot can't access Workflowy anymore.
A new session ID should be created and manually updated in the bot's code.

To fix this, the bot will have to check if its session ID is still valid, if it's not, then the bot should go and login to Workflowy and save the new session id.
