### ISSUE TITLE
/mapnewlist command is not configured

### ISSUE THREAD

**Issue by assafza** [WA-WF-Bot/Fredo-Public#104]
It used to work in the past but seems like its not now(In test bot
<img width="754" alt="Screen Shot 2022-04-24 at 11 06 37" src="https://user-images.githubusercontent.com/25544824/164966650-77539575-0d2e-4adb-ae0a-1521f6f75240.png">
)

**Comment by liatzionimorad** [comment]
@assafza @JerryVDP  please notice there is no need to implement such a command just follow the flow of adding #hashtag
![image](https://user-images.githubusercontent.com/79567202/164971538-7d827c4f-1066-426c-809b-8dca6f677154.png)

**Comment by assafza** [comment]
Correct!
It’s not being added to the help menu. Only here as a choice for the user.
