### ISSUE TITLE
#hashtag flow not responding

### ISSUE THREAD

**Issue by assafza** [WA-WF-Bot/Fredo-Public#105]
I started to create a new hashtag but the bot stopped responding when I sent the new shared link to the WF list
<img width="782" alt="Screen Shot 2022-04-24 at 12 11 07" src="https://user-images.githubusercontent.com/25544824/164969195-bb7747a9-8abc-40c1-8845-37d5e8ba8186.png">

**Comment by JerryVDP** [comment]
Elihai and I had to check and restart the server around ~12:00 PM, so that could be it...
