### ISSUE TITLE
/default flow for Trello

### ISSUE THREAD

**Issue by assafza** [WA-WF-Bot/Fredo-Public#111]
https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764524433196499&cot=14

@JerryVDP I have added the default unsupported answer text: https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764524932496844&cot=14

**Comment by assafza** [comment]
/default is stuck for some reason
<img width="749" alt="Screen Shot 2022-05-11 at 10 07 09" src="https://user-images.githubusercontent.com/25544824/167790110-ca549ba2-7b6e-419d-9071-88bd4ec11767.png">

**Comment by assafza** [comment]
Also after I type something in it is doing this error message:
<img width="754" alt="Screen Shot 2022-05-11 at 10 11 40" src="https://user-images.githubusercontent.com/25544824/167790511-ba37b80b-cf25-46d0-a716-bb86c1e9dbb6.png">

**Comment by JerryVDP** [comment]
It has nothing to do with us, so I'm moving this to done
