### ISSUE TITLE
Cosmetic Error - All  Instructions menu should be shown in the same type of font 

### ISSUE THREAD

**Issue by IvanTotti** [WA-WF-Bot/Fredo-Public#130]
**The setup instructions under number 2 - Trello and number 3 - Monday are written with BOLD font** ( BOARD, POWER-Ups etc.) ,but under set up instructions **number 4 for Workflowy the font is basic not Bold**.

It would look better if **all instructions menu would be written in the same type of font** - basic or bold so the whole Fredo bot looks compact visually.

![font2](https://user-images.githubusercontent.com/105730382/169272773-abca7e73-45cb-423e-8f65-e4df2bcc29d0.JPG)

**Comment by assafza** [comment]
Correct.
![Screen Shot 2022-05-22 at 13 48 17](https://user-images.githubusercontent.com/25544824/169691572-80c5738c-5b58-4af9-b963-7089213d7f4d.png)
