### ISSUE TITLE
WorkFlowy - Problem with connecting (link-paste) to Fredo once TRY AGAIN button is shown

### ISSUE THREAD

**Issue by IvanTotti** [WA-WF-Bot/Fredo-Public#132]
When incorrect link is inserted into Fredo from Workflowy we receive an error message:  **We could not connect to the provided link...** 

**Once the user tries to paste the link again he will again receive the same error message. The problem is solved only after the user directly clicks on TRY AGAIN button and afterwards paste the link.** 

**This should be fixed so the user is able to paste the link again and connect to Fredo without the need to click directly on the Try again button. OR the user should be informed that he needs at first to CLICK on TRY AGAIN button and only after that he will be able to paste the link again.**

![WORKFLOWY PROBLEM 1](https://user-images.githubusercontent.com/105730382/169285851-6b8fdc67-c12e-4da2-b5a6-18d00a245e3a.JPG)
![WORKFLOWY PROBLEM 11](https://user-images.githubusercontent.com/105730382/169285870-770355df-abdd-4772-a47d-f7d1ec8c2da9.JPG)

**Comment by assafza** [comment]
@JerryVDP I agree - the bot should accept also the list link if it was inserted again.
![Screen Shot 2022-05-22 at 13 45 12](https://user-images.githubusercontent.com/25544824/169691468-7eb637c1-fc77-4c47-acea-befdeeb0edc4.png)
