### ISSUE TITLE
/platform for Monday was not responsive

### ISSUE THREAD

**Issue by assafza** [WA-WF-Bot/Fredo-Public#138]
<img width="743" alt="Screen Shot 2022-05-26 at 13 07 25" src="https://user-images.githubusercontent.com/25544824/170466983-a970d8ec-da02-42a4-94c2-c633de03911e.png">

**Comment by JerryVDP** [comment]
Fixed missing translations ("responders/monday.current_platform_monday").
The other issue is Meser related as discussed.
