### ISSUE TITLE
#hashtag flow

### ISSUE THREAD

**Issue by ripper234** [WA-WF-Bot/Fredo-Public#79]
If you configure a list in one message, e.g.

![image](https://user-images.githubusercontent.com/172282/157929095-e91917d4-f5c2-4ca0-9024-979b854b5e69.png)

It's great that the list is indeed configured after the first message. Saves time.

But the wording on the first reply suggests the list isn't configured yet.
And that "I can ignore in order to continue normal operation" - which seems untrue (what does ignore mean).

I think the expected behavior, is - when we detecte a share link in the first message e.g.

#test123 https://workflowy.com/s/fredo-test111/7x4qMAeA5vNfjQWp

We should reply something like "#test123 successfully mapped to list".
(Not this specific wording, we should match the rest of the language already used)

**Comment by ripper234** [comment]
(The above example is from Test env)

**Comment by liatzionimorad** [comment]
@assafza  your view?

**Comment by assafza** [comment]
@elihaidv @liatzionimorad as we discussed the approach purposed by @ripper234 is accepted.

When a user sends #hashtag + Workflowy list link the system should try and map it.
If its successful show the current mapping successful message.
If it was not successful, show the message presented "I noticed you used #hashtag..." 
I think this can go into our current sprint.

**Comment by assafza** [comment]
I have added a flow in Miro for your review
https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764521874107870&cot=14

**Comment by liatzionimorad** [comment]
@JerryVDP Please re check the flow is not fully implemented as described in miro :
This is what I see:
![image](https://user-images.githubusercontent.com/79567202/161484028-7b5fe3f5-bcea-437a-a78a-93ddd90025d7.png)
 

This is what I expected to see:

![image](https://user-images.githubusercontent.com/79567202/161484160-37a7b7a9-a15e-4c5e-8cd4-bec413424f3d.png)

**Comment by liatzionimorad** [comment]
2 issues:
![image](https://user-images.githubusercontent.com/79567202/162157492-087325ea-598f-4f07-b3c7-f04c074d1721.png)
only single # should apear 

the second issue is the flow of #hastag which is not defined+ text
In this case after creating the link it should immediately state the text was added ( see flow) it does not:

![image](https://user-images.githubusercontent.com/79567202/162158068-dffc3660-210f-474c-abb8-5ab37389125c.png)

![image](https://user-images.githubusercontent.com/79567202/162158263-4cb600ca-f1d1-49d7-87cb-6273d1e2cee1.png)
