### ISSUE TITLE
Check mail interface options

### ISSUE THREAD

**Issue by liatzionimorad** [WA-WF-Bot/Fredo-Public#82]
We would like to check the option of sending PDF , png, jpg - as an attachment to the mail.

Please check if this is possible

**Comment by assafza** [comment]
@JerryVDP the task says we would check if it is possible.
You moved this to DONE, can you elaborate what are the findings you got? so we can have a record of your investigation.
(@liatzionimorad cc)

**Comment by JerryVDP** [comment]
@assafza 
As we discussed in the weekly meeting last week, we agreed that I'll make sure that the email channel can handle media messages and notify Liat when I'm done so she can test it. Currently, only images are supported in the infrastructure as elaborated by Elihai in the same meeting.

Before completing this task the email channel couldn't handle anything but text messages, now it can handle media messages as well.
