### ISSUE TITLE
Change the order and text inside /help menu (No added functionality)

### ISSUE THREAD

**Issue by assafza** [WA-WF-Bot/Fredo-Public#86]
Help menu should be printed as follow:

1. /listmaps - returns a list of all current #hashtag mappings.
2. /default - Choose a different Workflowy list to be set as Default list.
3. #urgent\#דחוף - Start a message with #urgent to put it in an "urgent tasks" list in WF to receive daily reminders.
4. #YOUR_HASHTAG- By starting a message using a hashtag you can place items to a specific list. (e.g. #grocery buy milk)
5. /bug - Allows you to submit a bug report
6. /cancel - Cancel current operation and connect you back to your Default list if exist
7. /delete - Erase all your login details.

@JerryVDP add Emoji's as you like to each item.

https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764519491476484&cot=14

**Comment by JerryVDP** [comment]
![image](https://user-images.githubusercontent.com/99589825/160361109-dda4d745-5fc8-4910-8bb8-79f006071823.png)
