### ISSUE TITLE
/listmaps command flow

### ISSUE THREAD

**Issue by assafza** [WA-WF-Bot/Fredo-Public#87]
It is very hard to understand currently how to add and manage multiple WF lists in Fredo.
I have added a flow for when a user decide to view /listmaps command.

https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764521872717842&cot=14

![Screen Shot 2022-03-27 at 13 45 43](https://user-images.githubusercontent.com/25544824/160277823-d20ffeaf-bf22-4c58-940e-dbfddf49a3b4.png)

**Comment by JerryVDP** [comment]
I've done implementing this, however this won't fully work as "Map new list" button depends on implementing the new hashtag flow (#79), which is not ready yet.
