### ISSUE TITLE
Confirmation on item added to list not displayed

### ISSUE THREAD

**Issue by liatzionimorad** [WA-WF-Bot/Fredo-Public#90]
Inserting all data from developers chat 
![image](https://user-images.githubusercontent.com/79567202/159867768-429ef4d3-b93e-4684-81be-9547a55e0719.png)

No confirmation received on the message.

![image](https://user-images.githubusercontent.com/79567202/159868164-0efcc8e2-9b86-43cd-893d-9262ca61cc36.png)

Currently under estimation

**Comment by JerryVDP** [comment]
I'll implement the above architecture and I'll add logs for any unsuccessful replies.

Estimate: ~10 hours.

**Comment by liatzionimorad** [comment]
Approved

**Comment by JerryVDP** [comment]
Returned this to "To do" column as I'm still waiting for an answer from MeserGo

**Comment by liatzionimorad** [comment]
@JerryVDP can you update?
