### ISSUE TITLE
few spelling and grammar fixes

### ISSUE THREAD

**Issue by assafza** [WA-WF-Bot/Fredo-Public#99]
1. help menu (see image)
<img width="799" alt="Screen Shot 2022-04-05 at 10 27 02" src="https://user-images.githubusercontent.com/25544824/161701449-3321275c-248f-48b4-a23b-9eaf713a9a6f.png">

2. /default text:
<img width="719" alt="Screen Shot 2022-04-05 at 10 29 21" src="https://user-images.githubusercontent.com/25544824/161702322-35785845-9f50-48b9-98d3-25309c214bee.png">

3. /mapnewlist text
<img width="879" alt="Screen Shot 2022-04-05 at 10 30 03" src="https://user-images.githubusercontent.com/25544824/161702387-26b7ef24-6be9-4f8f-8ede-046d04dabf19.png">

**Comment by liatzionimorad** [comment]
![image](https://user-images.githubusercontent.com/79567202/162156330-6567d894-260f-427a-9d45-685e226b75e0.png)
please remove the word "this"
